version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5005:5005"
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    volumes:
      - ./keys:/app/keys
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - blockchain_network
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: blockchain             
      MYSQL_PASSWORD: Bastiments2905!
      MYSQL_ROOT_PASSWORD: Bastiments2905!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - blockchain_network
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:

networks:
  blockchain_network:
    driver: bridge